### PR TITLE
update deps for babel-plugin-transform-es2015-generator-return

### LINKED ISSUE #8: RangeError while using `babel-plugin-transform-es2015-generator-return` and `babel-plugin-transform-es2015-block-scoping` together
hax/babel-plugin-transform-es2015-generator-return#24

### PR DESCRIPTION
**Pull request by soulwu**
fix #8

### CODE REVIEW

**Comment by ariporad** [comment]
Hey, @soulwu,

I've noticed you've been pretty active with this project. Since I don't really have time to maintain it, would you like to take it over? (If you don't want to, that's totally OK too).

**Comment by soulwu** [comment]
@ariporad OK, I can help you to maintain it together. 😄

**Comment by ariporad** [comment]
@soulwu: Great.

First thing you should know, (before I merge this PR), I've been using [`semantic-release`](http://npm.im/semantic-release) for releases. You're more than welcome to get rid of this system (I'll add you to npm), but if you want to leave it the way it is, could you please update the commit messages to comply with the guidelines?

Thanks so much!

**Comment by soulwu** [comment]
@ariporad Fine, I would get more knowledge about [semantic-release](http://npm.im/semantic-release) first~

**Pull request merged**
